language: elixir
elixir:
  - 1.5
script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
