language: elixir
elixir:
  - 1.5
cache:
  directories:
    - _build
    - deps
script:
  - MIX_ENV=test mix credo
  - MIX_ENV=test mix do compile, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
